<?php

declare(strict_types=1);

namespace ZephyrPHP\Cms\Services;

use ZephyrPHP\Cms\Models\Collection;
use ZephyrPHP\Cms\Models\Field;

class SeoService
{
    /**
     * SEO column definitions for dynamic collection tables.
     */
    public const SEO_COLUMNS = [
        'meta_title' => 'VARCHAR(255) NULL DEFAULT NULL',
        'meta_description' => 'TEXT NULL DEFAULT NULL',
        'og_image' => 'VARCHAR(500) NULL DEFAULT NULL',
        'canonical_url' => 'VARCHAR(500) NULL DEFAULT NULL',
        'robots' => "VARCHAR(100) NULL DEFAULT 'index,follow'",
    ];

    /**
     * Get resolved SEO metadata for an entry.
     * Manual values take priority; auto-generates from entry data if empty.
     */
    public static function getEntryMeta(array $entry, Collection $collection): array
    {
        $meta = [
            'title' => '',
            'description' => '',
            'og_image' => '',
            'canonical_url' => '',
            'robots' => 'index,follow',
        ];

        if (!$collection->isSeoEnabled()) {
            return $meta;
        }

        // Use manual values if set
        $meta['title'] = trim($entry['meta_title'] ?? '');
        $meta['description'] = trim($entry['meta_description'] ?? '');
        $meta['og_image'] = trim($entry['og_image'] ?? '');
        $meta['canonical_url'] = trim($entry['canonical_url'] ?? '');
        $meta['robots'] = trim($entry['robots'] ?? 'index,follow');

        // Auto-generate title from first text field if empty
        if (empty($meta['title'])) {
            $meta['title'] = self::autoGenerateTitle($entry, $collection);
        }

        // Auto-generate description from first textarea/richtext field if empty
        if (empty($meta['description'])) {
            $meta['description'] = self::autoGenerateDescription($entry, $collection);
        }

        return $meta;
    }

    /**
     * Auto-generate a meta title from the entry's first text field value.
     */
    public static function autoGenerateTitle(array $entry, Collection $collection): string
    {
        $fields = $collection->getFields()->toArray();

        // Prefer fields named title/name/heading
        $preferredSlugs = ['title', 'name', 'heading', 'subject'];
        foreach ($preferredSlugs as $slug) {
            if (!empty($entry[$slug]) && is_string($entry[$slug])) {
                return self::truncate($entry[$slug], 60);
            }
        }

        // Fall back to first text-type field
        foreach ($fields as $field) {
            if (in_array($field->getType(), ['text', 'email']) && !empty($entry[$field->getSlug()])) {
                return self::truncate((string) $entry[$field->getSlug()], 60);
            }
        }

        return '';
    }

    /**
     * Auto-generate a meta description from the entry's first long-text field.
     */
    public static function autoGenerateDescription(array $entry, Collection $collection): string
    {
        $fields = $collection->getFields()->toArray();

        // Prefer fields named description/excerpt/summary/body/content
        $preferredSlugs = ['description', 'excerpt', 'summary', 'body', 'content'];
        foreach ($preferredSlugs as $slug) {
            if (!empty($entry[$slug]) && is_string($entry[$slug])) {
                return self::truncate(strip_tags($entry[$slug]), 160);
            }
        }

        // Fall back to first textarea/richtext field
        foreach ($fields as $field) {
            if (in_array($field->getType(), ['textarea', 'richtext']) && !empty($entry[$field->getSlug()])) {
                return self::truncate(strip_tags((string) $entry[$field->getSlug()]), 160);
            }
        }

        return '';
    }

    /**
     * Generate JSON-LD structured data for an entry.
     */
    public static function generateJsonLd(array $entry, Collection $collection, string $baseUrl = ''): string
    {
        $meta = self::getEntryMeta($entry, $collection);

        $jsonLd = [
            '@context' => 'https://schema.org',
            '@type' => 'WebPage',
            'name' => $meta['title'] ?: ($entry['title'] ?? $entry['name'] ?? ''),
            'description' => $meta['description'],
        ];

        // URL
        if (!empty($meta['canonical_url'])) {
            $jsonLd['url'] = $meta['canonical_url'];
        } elseif (!empty($baseUrl) && !empty($entry['slug'])) {
            $prefix = $collection->getUrlPrefix();
            if ($prefix) {
                $jsonLd['url'] = rtrim($baseUrl, '/') . '/' . ltrim($prefix, '/') . '/' . $entry['slug'];
            }
        }

        // Image
        if (!empty($meta['og_image'])) {
            $jsonLd['image'] = $meta['og_image'];
        }

        // Dates
        if (!empty($entry['created_at'])) {
            $jsonLd['dateCreated'] = $entry['created_at'];
        }
        if (!empty($entry['updated_at'])) {
            $jsonLd['dateModified'] = $entry['updated_at'];
        }
        if (!empty($entry['published_at'])) {
            $jsonLd['datePublished'] = $entry['published_at'];
            $jsonLd['@type'] = 'Article';
        }

        return json_encode($jsonLd, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
    }

    /**
     * Calculate an SEO score (0–100) for an entry.
     * Returns score and array of issues.
     */
    public static function calculateSeoScore(array $entry, Collection $collection): array
    {
        $score = 0;
        $issues = [];
        $maxScore = 0;

        if (!$collection->isSeoEnabled()) {
            return ['score' => 0, 'issues' => ['SEO is not enabled for this collection.']];
        }

        // 1. Meta title (25 points)
        $maxScore += 25;
        $title = trim($entry['meta_title'] ?? '');
        if (empty($title)) {
            // Check auto-generated
            $title = self::autoGenerateTitle($entry, $collection);
            if (!empty($title)) {
                $score += 10;
                $issues[] = 'Meta title is auto-generated. Set a custom title for better SEO.';
            } else {
                $issues[] = 'Missing meta title.';
            }
        } else {
            $titleLen = mb_strlen($title);
            if ($titleLen >= 30 && $titleLen <= 60) {
                $score += 25;
            } elseif ($titleLen > 0 && $titleLen < 30) {
                $score += 15;
                $issues[] = "Meta title is short ({$titleLen} chars). Aim for 30–60 characters.";
            } elseif ($titleLen > 60) {
                $score += 15;
                $issues[] = "Meta title is long ({$titleLen} chars). Keep it under 60 characters.";
            }
        }

        // 2. Meta description (25 points)
        $maxScore += 25;
        $desc = trim($entry['meta_description'] ?? '');
        if (empty($desc)) {
            $desc = self::autoGenerateDescription($entry, $collection);
            if (!empty($desc)) {
                $score += 10;
                $issues[] = 'Meta description is auto-generated. Set a custom description for better SEO.';
            } else {
                $issues[] = 'Missing meta description.';
            }
        } else {
            $descLen = mb_strlen($desc);
            if ($descLen >= 120 && $descLen <= 160) {
                $score += 25;
            } elseif ($descLen > 0 && $descLen < 120) {
                $score += 15;
                $issues[] = "Meta description is short ({$descLen} chars). Aim for 120–160 characters.";
            } elseif ($descLen > 160) {
                $score += 15;
                $issues[] = "Meta description is long ({$descLen} chars). Keep it under 160 characters.";
            }
        }

        // 3. OG Image (20 points)
        $maxScore += 20;
        if (!empty($entry['og_image'])) {
            $score += 20;
        } else {
            $issues[] = 'No Open Graph image set. Social media shares will lack a preview image.';
        }

        // 4. Slug readability (15 points)
        $maxScore += 15;
        if (!empty($entry['slug'])) {
            $slug = $entry['slug'];
            if (mb_strlen($slug) <= 60 && preg_match('/^[a-z0-9]+(-[a-z0-9]+)*$/', $slug)) {
                $score += 15;
            } elseif (mb_strlen($slug) > 60) {
                $score += 8;
                $issues[] = 'URL slug is long. Shorter slugs tend to rank better.';
            } else {
                $score += 10;
            }
        }

        // 5. Canonical URL (15 points)
        $maxScore += 15;
        if (!empty($entry['canonical_url'])) {
            if (filter_var($entry['canonical_url'], FILTER_VALIDATE_URL)) {
                $score += 15;
            } else {
                $score += 5;
                $issues[] = 'Canonical URL is not a valid URL.';
            }
        } else {
            $score += 10; // Not required but nice to have
        }

        $finalScore = $maxScore > 0 ? (int) round(($score / $maxScore) * 100) : 0;

        return [
            'score' => $finalScore,
            'issues' => $issues,
        ];
    }

    /**
     * Build HTML meta tags string from resolved SEO data.
     */
    public static function buildMetaTags(array $meta, string $siteName = ''): string
    {
        $html = '';

        if (!empty($meta['title'])) {
            $title = htmlspecialchars($meta['title'], ENT_QUOTES, 'UTF-8');
            $html .= '<meta name="title" content="' . $title . '">' . "\n";
        }

        if (!empty($meta['description'])) {
            $desc = htmlspecialchars($meta['description'], ENT_QUOTES, 'UTF-8');
            $html .= '<meta name="description" content="' . $desc . '">' . "\n";
        }

        if (!empty($meta['robots'])) {
            $html .= '<meta name="robots" content="' . htmlspecialchars($meta['robots'], ENT_QUOTES, 'UTF-8') . '">' . "\n";
        }

        if (!empty($meta['canonical_url'])) {
            $html .= '<link rel="canonical" href="' . htmlspecialchars($meta['canonical_url'], ENT_QUOTES, 'UTF-8') . '">' . "\n";
        }

        return $html;
    }

    /**
     * Build Open Graph meta tags.
     */
    public static function buildOgTags(array $meta, string $url = '', string $siteName = ''): string
    {
        $html = '';

        if (!empty($meta['title'])) {
            $html .= '<meta property="og:title" content="' . htmlspecialchars($meta['title'], ENT_QUOTES, 'UTF-8') . '">' . "\n";
        }

        if (!empty($meta['description'])) {
            $html .= '<meta property="og:description" content="' . htmlspecialchars($meta['description'], ENT_QUOTES, 'UTF-8') . '">' . "\n";
        }

        if (!empty($meta['og_image'])) {
            $html .= '<meta property="og:image" content="' . htmlspecialchars($meta['og_image'], ENT_QUOTES, 'UTF-8') . '">' . "\n";
        }

        $html .= '<meta property="og:type" content="article">' . "\n";

        if (!empty($url)) {
            $html .= '<meta property="og:url" content="' . htmlspecialchars($url, ENT_QUOTES, 'UTF-8') . '">' . "\n";
        } elseif (!empty($meta['canonical_url'])) {
            $html .= '<meta property="og:url" content="' . htmlspecialchars($meta['canonical_url'], ENT_QUOTES, 'UTF-8') . '">' . "\n";
        }

        if (!empty($siteName)) {
            $html .= '<meta property="og:site_name" content="' . htmlspecialchars($siteName, ENT_QUOTES, 'UTF-8') . '">' . "\n";
        }

        return $html;
    }

    /**
     * Truncate a string to a maximum length, breaking at word boundaries.
     */
    private static function truncate(string $text, int $maxLength): string
    {
        $text = trim(preg_replace('/\s+/', ' ', $text));

        if (mb_strlen($text) <= $maxLength) {
            return $text;
        }

        $truncated = mb_substr($text, 0, $maxLength);
        $lastSpace = mb_strrpos($truncated, ' ');

        if ($lastSpace !== false && $lastSpace > $maxLength * 0.7) {
            $truncated = mb_substr($truncated, 0, $lastSpace);
        }

        return $truncated;
    }
}
